// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rvdoynpqmfezmxlngvgq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2ZG95bnBxbWZlem14bG5ndmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE3MzMzNjYsImV4cCI6MjA0NzMwOTM2Nn0.ds2zVcrEYhoOIRsYNLdwaRDfynzvrhKuqKqA3q5zKE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);